export interface Attachment {
    name: string;
    url: string;
    type: string;
}

export interface AdminOccurrenceRecord {
    id: string;
    protocolo: string;
    descricao: string;
    criado_por: string;
    created_at: string;
    criado_em?: string;
    tenant_id: string;
    employee_name: string;
    type: string;
    subtype: string;
    attachments: Attachment[]; // JSONB
    coordinator_signature_path: string | null;
    employee_signature_path: string | null;
    status: string;
    signed_at: string | null;
    occurrence_date: string;
    titulo?: string;
    tipo?: string;
    subtipo?: string;
    paciente_nome_completo?: string;
    paciente_telefone?: string;
    paciente_id?: string;
    paciente_data_nascimento?: string;
    paciente_tipo_exame?: string;
    paciente_unidade_local?: string;
    paciente_data_hora_evento?: string;
    descricao_detalhada?: string;
    acao_imediata?: string;
    impacto_percebido?: string;
    pessoas_envolvidas?: string;
    contem_dado_sensivel?: boolean;
    triagem?: string;
    triagem_por?: string;
    triagem_em?: string;
    desfecho_tipos?: string[];
    desfecho_justificativa?: string;
    desfecho_principal?: string;
    desfecho_definido_por?: string;
    desfecho_definido_em?: string;
    notificacao_orgao?: string;
    notificacao_data?: string;
    notificacao_responsavel?: string;
    notificacao_anexo_url?: string;
    atualizado_em?: string;
    pdf_conclusao_url?: string;
    pdf_gerado_em?: string;
    dados_especificos?: any;
    registrador_setor?: string;
    registrador_cargo?: string;
    houve_dano?: boolean;
    descricao_dano?: string;
    pessoas_comunicadas?: string;
    observacoes?: string;
    acoes_imediatas_checklist?: any;
    public_token?: string;
    medico_destino?: string;
    mensagem_admin_medico?: string;
    mensagem_medico?: string;
    encaminhada_em?: string;
    finalizada_em?: string;
    "paciente-sexo"?: string;
    paciente_sexo?: string;
    custom_type?: string;
    related_employee_id?: string;
    medical_analysis_status?: string;
    medical_analysis_completed_at?: string;
    medical_doctor_id?: string;
    medical_doctor_name?: string;
    medical_analysis_result?: string;
    medical_analysis_note?: string;
    triage_classification?: string;
    triage_impact?: string;
    triage_recurrence?: string;
    triage_completed_at?: string;
    triage_by_user_id?: string;
    outcome_actions?: string[];
    outcome_note?: string;
    outcome_completed_at?: string;
    outcome_by_user_id?: string;
    finalizado_por?: string;
    origin?: string;
    paciente_nome?: string;
    categoria?: string;
}
